services:
  web:
    build: .
    environment:
      - SSH_HOST=coljac.info
      - SSH_PORT=22
    ports:
    - "8888:8888"

  nginx:
    profiles:
      - production
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web
